export const ROUTE_PATH = {
  HOME: '',
  TRIPS: 'trips',
  PLAN_TRIP: 'plan-trip',
  CREATE_TRIP: 'create-trip',
  INVITATIONS: 'invitations',
  TRIP_INVITATION: 'invitation',
  SHARED_ITINERARY: 'shared-itinerary',
  OVERVIEW: `plan-trip/overview`,
  INVITE: 'plan-trip/invite',
  ITINERARY: 'plan-trip/itinerary',
  TRIP_LIST: 'plan-trip/trip-list',
  TO_DO_LIST: 'plan-trip/to-do-list',
  MANAGE_EXPENSES: 'plan-trip/manage-expenses',
  CHAT: 'plan-trip/chat',
  DOCUMENTS: 'plan-trip/documents',
  LOCATION_SHARING: 'plan-trip/location-sharing',
  SETTINGS: 'plan-trip/settings',
  GROUP_CALL: 'plan-trip/group-call',
};
