export const ROUTE_PATH = {
  HOME: '',
  TRIPS: 'trips',
  PLAN_TRIP: 'plan-trip',
  CREATE_TRIP: 'create-trip',
  INVITATIONS: 'invitations',
  TRIP_INVITATION: 'invitation',
  OVERVIEW: `plan-trip/overview`,
  INVITE: 'plan-trip/invite',
  ITINERARY: 'plan-trip/itinerary',
  PACKAGING_LIST: 'plan-trip/packaging-list',
  TO_DO_LIST: 'plan-trip/to-do-list',
  BUDGET: 'plan-trip/budget',
  CHAT: 'plan-trip/chat',
  DOCUMENTS: 'plan-trip/documents',
  SETTINGS: 'plan-trip/settings',
};
